

services:
  master1:
    image: seatunnel-2.3.11-kas:latest
    hostname: seatunnel-master1
    container_name: seatunnel-master1
    env_file:
      - ./docker-compose.env

    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r master
      "    
    ports:
      - "8080:8080"
      - "8443:8443"
#       - "5801:5801"
    volumes:
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./config:/opt/seatunnel/config
      # - ./connectors:/opt/seatunnel/connectors
      - ./key_store:/key_store
    networks:
      integration:
        ipv4_address: 172.199.0.50

  worker1:
    image: seatunnel-2.3.11-kas:latest
    hostname: seatunnel-worker-1
    container_name: seatunnel-worker-1
    env_file:
      - ./docker-compose.env

    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r worker
      " 
    volumes:
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./config:/opt/seatunnel/config
      # - ./connectors:/opt/seatunnel/connectors
      - ./key_store:/key_store
    depends_on:
      - master1
    networks:
      integration:
        ipv4_address: 172.199.0.51


  mysql:
    image: seatunnel-mysql:0.1.0
    hostname: seatunnel-mysql
    container_name: seatunnel-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Abcd1234
      MYSQL_DATABASE: seatunnel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      integration:
        ipv4_address: 172.199.0.60


networks:
  integration:
    external: true

volumes:
  mysql_data:
  seatunnel_master1_data:
  seatunnel_worker1_data:
  seatunnel_worker2_data:
  seatunnel_logs:
