

services:
  master1:
    image: quay.io/larryloi/seatunnel-2.3.10-kas:latest
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile-seatunnel-kas
    hostname: seatunnel-master1
    container_name: seatunnel-master1
    environment:
      - TZ=Asia/Macau
      - ST_DOCKER_MEMBER_LIST=172.199.0.50
      - SRC_DB_USER=seatunnel_src
      - SRC_DB_PASSWORD=Abcd1234
      - SINK_DB_USER=seatunnel_sink
      - SINK_DB_PASSWORD=Abcd1234
      # - JAVA_CLASSPATH=/opt/seatunnel/lib:/opt/seatunnel/starter
        #- IJAVA_CLASSPATH=/opt/seatunnel/lib
      #- JAVA_CLASSPATH=/opt/seatunnel/lib
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r master
      "    
    ports:
      - "5801:5801"
      - "5701:5701"
    volumes:
      - ./config:/opt/seatunnel/config/config
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./key_store:/key_store
    networks:
      integration:
        ipv4_address: 172.199.0.50


  mysql:
    image: seatunnel-mysql:0.1.0
    hostname: seatunnel-mysql
    container_name: seatunnel-mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: Abcd1234
      MYSQL_DATABASE: seatunnel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      integration:
        ipv4_address: 172.199.0.60



networks:
  integration:
    external: true

volumes:
  mysql_data:
  seatunnel_master1_data:
  seatunnel_worker1_data:
  seatunnel_worker2_data:
  seatunnel_logs:
