

services:
  master1:
    image: quay.io/larryloi/seatunnel-2.3.10-kas:latest
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile-seatunnel-kas
    hostname: seatunnel-master1
    container_name: seatunnel-master1
    env_file:
      - ./docker-compose.env
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r master
      "    
    ports:
      - "5801:5801"
      - "8080:8080"
    volumes:
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./config:/opt/seatunnel/config/config
      #- ./connectors:/opt/seatunnel/connectors
      - ./key_store:/key_store
    networks:
      integration:
        ipv4_address: 172.199.0.50

  worker1:
    image: quay.io/larryloi/seatunnel-2.3.10-kas:latest
    hostname: seatunnel-worker-1
    container_name: seatunnel-worker-1
    env_file:
      - ./docker-compose.env
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r worker
      " 
    volumes:
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./config:/opt/seatunnel/config/config
      # - ./connectors:/opt/seatunnel/connectors
      - ./key_store:/key_store
    depends_on:
      - master1
    networks:
      integration:
        ipv4_address: 172.199.0.51

  worker2:
    image: quay.io/larryloi/seatunnel-2.3.10-kas:latest
    hostname: seatunnel-worker-2
    container_name: seatunnel-worker-2
    env_file:
      - ./docker-compose.env
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r worker 
      " 
    volumes:
      - ./JOBS:/opt/seatunnel/JOBS
      - ./Makefile.ct:/opt/seatunnel/Makefile
      - ./config:/opt/seatunnel/config/config
      # - ./connectors:/opt/seatunnel/connectors
      - ./key_store:/key_store
    depends_on:
      - master1
    networks:
      integration:
        ipv4_address: 172.199.0.52



networks:
  integration:
    external: true

volumes:
  mysql_data:
  seatunnel_master1_data:
  seatunnel_worker1_data:
  seatunnel_worker2_data:
  seatunnel_logs:
