

services:
  master:
    image: apache/seatunnel
    container_name: seatunnel-master
    environment:
      - TZ=Asia/Macau
      - ST_DOCKER_MEMBER_LIST=172.16.0.2,172.16.0.3,172.16.0.4    
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r master -DJvmOption=\"-Xms2G -Xmx2G\"
      "    
    ports:
      - "5701:5701"
    volumes:
      - ./config:/opt/seatunnel/config
      - ./job:/opt/seatunnel/job
    networks:
      seatunnel-network:
        ipv4_address: 172.16.0.2

  worker1:
    image: apache/seatunnel
    container_name: seatunnel-worker-1
    environment:
      - TZ=Asia/Macau
      - ST_DOCKER_MEMBER_LIST=172.16.0.2,172.16.0.3,172.16.0.4
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r worker -DJvmOption=\"-Xms2G -Xmx2G\"
      " 
    volumes:
      - ./config:/opt/seatunnel/config
    depends_on:
      - master
    networks:
      seatunnel-network:
        ipv4_address: 172.16.0.3

  worker2:
    image: apache/seatunnel
    container_name: seatunnel-worker-2
    environment:
      - TZ=Asia/Macau
      - ST_DOCKER_MEMBER_LIST=172.16.0.2,172.16.0.3,172.16.0.4
    entrypoint: >
      /bin/sh -c "
      /opt/seatunnel/bin/seatunnel-cluster.sh -r worker -DJvmOption=\"-Xms2G -Xmx2G\"
      " 
    volumes:
      - ./config:/opt/seatunnel/config
    depends_on:
      - master
    networks:
      seatunnel-network:
        ipv4_address: 172.16.0.4

  mysql:
    build:
      context: ./mysql
    container_name: seatunnel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: seatunnel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      seatunnel-network:
        ipv4_address: 172.16.0.200

  web:
    build:
      context: ./seatunnel-web
    container_name: seatunnel-web
    environment:
      - SEATUNNEL_MASTER_HOST=172.16.0.2
      - MYSQL_HOST=172.16.0.200
      - MYSQL_PORT=3306
      - MYSQL_DB=seatunnel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - "8080:8080"
      - "8801:8801"
    networks:
      seatunnel-network:
        ipv4_address: 172.16.0.210
    depends_on:
      - master
      - mysql
    volumes:
      - ./seatunnel-web/application.yml:/app/conf/application.yml

networks:
  seatunnel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

volumes:
  mysql_data:
